<?php

namespace App\Services;

use App\Models\System;
use App\Models\SystemDocument;
use App\Support\SystemDocumentTypes;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class SystemMarkdownGenerator
{
    /** @return array<string, string> */
    public function availableTypes(): array
    {
        return SystemDocumentTypes::all();
    }

    public function generate(System $system, string $type): string
    {
        if (! SystemDocumentTypes::isValid($type)) {
            throw new \InvalidArgumentException("Unknown document type: {$type}");
        }

        $system = $this->loadSystem($system);

        if ($type === SystemDocumentTypes::FULL) {
            return $this->buildFullDocument($system);
        }

        return match ($type) {
            SystemDocumentTypes::OVERVIEW => $this->buildOverview($system),
            SystemDocumentTypes::API_CATALOG => $this->buildApiCatalog($system),
            SystemDocumentTypes::INTEGRATIONS => $this->buildIntegrations($system),
            SystemDocumentTypes::TECHNOLOGY_STACK => $this->buildTechnologyStack($system),
            SystemDocumentTypes::INFRASTRUCTURE => $this->buildInfrastructure($system),
            SystemDocumentTypes::PROCESSES => $this->buildProcesses($system),
            SystemDocumentTypes::DATA_SCHEMAS => $this->buildDataSchemas($system),
        };
    }

    public function persist(System $system, string $type, ?string $version = null): SystemDocument
    {
        $content = $this->generate($system, $type);
        $filename = SystemDocumentTypes::filename($type, $system->name);
        $path = "system-documents/{$system->id}/{$filename}";

        $existing = $system->documents()
            ->where('attachment_original_name', $filename)
            ->first();

        if ($existing) {
            $existing->deleteAttachment();
        }

        Storage::disk('local')->put($path, $content);

        return SystemDocument::updateOrCreate(
            [
                'system_id' => $system->id,
                'attachment_original_name' => $filename,
            ],
            [
                'name' => SystemDocumentTypes::label($type),
                'version' => $version ?? now()->format('Y.m.d'),
                'attachment_path' => $path,
            ]
        );
    }

    private function loadSystem(System $system): System
    {
        return $system->load([
            'vendor',
            'domain',
            'parent',
            'children',
            'ownedApis.versions.restDetail',
            'ownedApis.versions.soapDetail',
            'ownedApis.systems.vendor',
            'technologies',
            'servers',
            'bpmns',
            'platformSchemas.fields',
            'documents',
        ]);
    }

    private function buildFullDocument(System $system): string
    {
        $sections = [
            SystemDocumentTypes::OVERVIEW,
            SystemDocumentTypes::API_CATALOG,
            SystemDocumentTypes::INTEGRATIONS,
            SystemDocumentTypes::TECHNOLOGY_STACK,
            SystemDocumentTypes::INFRASTRUCTURE,
            SystemDocumentTypes::PROCESSES,
            SystemDocumentTypes::DATA_SCHEMAS,
        ];

        $parts = [
            '# '.$this->escape($system->name).' — Complete Documentation',
            '',
            '> Auto-generated by OpenITS on '.now()->format('Y-m-d H:i').' UTC',
            '',
        ];

        foreach ($sections as $section) {
            $body = match ($section) {
                SystemDocumentTypes::OVERVIEW => $this->buildOverviewBody($system),
                SystemDocumentTypes::API_CATALOG => $this->buildApiCatalogBody($system),
                SystemDocumentTypes::INTEGRATIONS => $this->buildIntegrationsBody($system),
                SystemDocumentTypes::TECHNOLOGY_STACK => $this->buildTechnologyStackBody($system),
                SystemDocumentTypes::INFRASTRUCTURE => $this->buildInfrastructureBody($system),
                SystemDocumentTypes::PROCESSES => $this->buildProcessesBody($system),
                SystemDocumentTypes::DATA_SCHEMAS => $this->buildDataSchemasBody($system),
            };

            $parts[] = '---';
            $parts[] = '';
            $parts[] = '## '.SystemDocumentTypes::label($section);
            $parts[] = '';
            $parts = array_merge($parts, $body);
            $parts[] = '';
        }

        return implode("\n", $parts);
    }

    private function buildOverview(System $system): string
    {
        return $this->wrapDocument($system, SystemDocumentTypes::OVERVIEW, $this->buildOverviewBody($system));
    }

    /** @return list<string> */
    private function buildOverviewBody(System $system): array
    {
        $lines = [
            '## Overview',
            '',
            $system->description ? $this->escape($system->description) : '_No description provided._',
            '',
            '## Metadata',
            '',
            '| Field | Value |',
            '| --- | --- |',
            '| **Name** | '.$this->escape($system->name).' |',
            '| **Type** | '.($system->system_type ? $this->escape($system->system_type) : '—').' |',
            '| **Vendor** | '.($system->vendor ? $this->escape($system->vendor->name) : '—').' |',
            '| **Domain** | '.($system->domain ? $this->escape($system->domain->name) : '—').' |',
            '| **Parent System** | '.($system->parent ? $this->escape($system->parent->name) : '—').' |',
        ];

        if ($system->children->isNotEmpty()) {
            $lines[] = '';
            $lines[] = '## Child Systems';
            $lines[] = '';
            foreach ($system->children as $child) {
                $lines[] = '- '.$this->escape($child->name).($child->system_type ? ' (`'.$this->escape($child->system_type).'`)' : '');
            }
        }

        $lines[] = '';
        $lines[] = '## Summary';
        $lines[] = '';
        $lines[] = '| Area | Count |';
        $lines[] = '| --- | ---: |';
        $lines[] = '| APIs | '.$system->ownedApis->count().' |';
        $lines[] = '| Technologies | '.$system->technologies->count().' |';
        $lines[] = '| Servers | '.$system->servers->count().' |';
        $lines[] = '| Processes | '.$system->bpmns->count().' |';
        $lines[] = '| Data Schemas | '.$system->platformSchemas->count().' |';
        $lines[] = '| Documents | '.$system->documents->count().' |';

        return $lines;
    }

    private function buildApiCatalog(System $system): string
    {
        return $this->wrapDocument($system, SystemDocumentTypes::API_CATALOG, $this->buildApiCatalogBody($system));
    }

    /** @return list<string> */
    private function buildApiCatalogBody(System $system): array
    {
        if ($system->ownedApis->isEmpty()) {
            return ['_No APIs registered for this system._'];
        }

        $lines = [];

        foreach ($system->ownedApis as $api) {
            $lines[] = '### '.$this->escape($api->name);
            $lines[] = '';
            $lines[] = '- **Type:** `'.strtoupper($this->escape($api->type)).'`';

            if ($api->description) {
                $lines[] = '- **Description:** '.$this->escape($api->description);
            }

            $version = $api->versions->first();

            if (! $version) {
                $lines[] = '- **Versions:** _No versions configured._';
                $lines[] = '';

                continue;
            }

            $lines[] = '- **Default Version:** `'.$this->escape($version->version).'`';
            $lines[] = '- **Status:** `'.$this->escape($version->status).'`';

            if ($version->endpoint_url) {
                $lines[] = '- **Endpoint:** `'.$this->escape($version->endpoint_url).'`';
            }

            if ($version->authentication_type) {
                $lines[] = '- **Authentication:** '.$this->escape($version->authentication_type);
            }

            if ($version->restDetail?->http_method) {
                $lines[] = '- **HTTP Method:** `'.strtoupper($this->escape($version->restDetail->http_method)).'`';
            }

            if ($version->soapDetail?->wsdl_url) {
                $lines[] = '- **WSDL:** `'.$this->escape($version->soapDetail->wsdl_url).'`';
            }

            if ($api->systems->isNotEmpty()) {
                $consumers = $api->systems
                    ->where('id', '!=', $system->id)
                    ->pluck('name')
                    ->map(fn ($name) => $this->escape($name))
                    ->implode(', ');

                if ($consumers !== '') {
                    $lines[] = '- **Consumer Systems:** '.$consumers;
                }
            }

            if ($api->versions->count() > 1) {
                $lines[] = '';
                $lines[] = '#### Versions';
                $lines[] = '';
                $lines[] = '| Version | Status | Endpoint |';
                $lines[] = '| --- | --- | --- |';

                foreach ($api->versions as $apiVersion) {
                    $lines[] = '| `'.$this->escape($apiVersion->version).'` | '
                        .$this->escape($apiVersion->status).' | '
                        .($apiVersion->endpoint_url ? '`'.$this->escape($apiVersion->endpoint_url).'`' : '—').' |';
                }
            }

            $lines[] = '';
        }

        return $lines;
    }

    private function buildIntegrations(System $system): string
    {
        return $this->wrapDocument($system, SystemDocumentTypes::INTEGRATIONS, $this->buildIntegrationsBody($system));
    }

    /** @return list<string> */
    private function buildIntegrationsBody(System $system): array
    {
        $outbound = [];
        $inbound = [];

        foreach ($system->ownedApis as $api) {
            foreach ($api->systems->where('id', '!=', $system->id) as $consumer) {
                $outbound[] = [
                    'api' => $api->name,
                    'type' => strtoupper($api->type),
                    'system' => $consumer->name,
                    'vendor' => $consumer->vendor?->name,
                ];
            }
        }

        $consumedApis = $system->apis()
            ->with(['ownerSystem.vendor', 'versions'])
            ->where('owner_system_id', '!=', $system->id)
            ->get();

        foreach ($consumedApis as $api) {
            $inbound[] = [
                'api' => $api->name,
                'type' => strtoupper($api->type),
                'system' => $api->ownerSystem?->name ?? 'Unknown',
                'vendor' => $api->ownerSystem?->vendor?->name,
            ];
        }

        if ($outbound === [] && $inbound === []) {
            return ['_No cross-system integrations documented for this system._'];
        }

        $lines = [];

        if ($outbound !== []) {
            $lines[] = '## Outbound (this system provides)';
            $lines[] = '';
            $lines[] = '| API | Type | Consumer System | Vendor |';
            $lines[] = '| --- | --- | --- | --- |';

            foreach ($outbound as $row) {
                $lines[] = '| '.$this->escape($row['api']).' | `'.$this->escape($row['type']).'` | '
                    .$this->escape($row['system']).' | '
                    .($row['vendor'] ? $this->escape($row['vendor']) : '—').' |';
            }

            $lines[] = '';
        }

        if ($inbound !== []) {
            $lines[] = '## Inbound (this system consumes)';
            $lines[] = '';
            $lines[] = '| API | Type | Provider System | Vendor |';
            $lines[] = '| --- | --- | --- | --- |';

            foreach ($inbound as $row) {
                $lines[] = '| '.$this->escape($row['api']).' | `'.$this->escape($row['type']).'` | '
                    .$this->escape($row['system']).' | '
                    .($row['vendor'] ? $this->escape($row['vendor']) : '—').' |';
            }
        }

        return $lines;
    }

    private function buildTechnologyStack(System $system): string
    {
        return $this->wrapDocument($system, SystemDocumentTypes::TECHNOLOGY_STACK, $this->buildTechnologyStackBody($system));
    }

    /** @return list<string> */
    private function buildTechnologyStackBody(System $system): array
    {
        if ($system->technologies->isEmpty()) {
            return ['_No technologies cataloged for this system._'];
        }

        $lines = [
            '| Technology | Category | Version |',
            '| --- | --- | --- |',
        ];

        foreach ($system->technologies as $technology) {
            $lines[] = '| '.$this->escape($technology->name).' | '
                .($technology->category ? $this->escape($technology->category) : '—').' | '
                .($technology->pivot->version ? '`'.$this->escape($technology->pivot->version).'`' : '—').' |';
        }

        return $lines;
    }

    private function buildInfrastructure(System $system): string
    {
        return $this->wrapDocument($system, SystemDocumentTypes::INFRASTRUCTURE, $this->buildInfrastructureBody($system));
    }

    /** @return list<string> */
    private function buildInfrastructureBody(System $system): array
    {
        if ($system->servers->isEmpty()) {
            return ['_No servers registered for this system._'];
        }

        $lines = [
            '| Server | Type | Hostname | IP | Port | Location |',
            '| --- | --- | --- | --- | --- | --- |',
        ];

        foreach ($system->servers as $server) {
            $lines[] = '| '.$this->escape($server->displayName()).' | '
                .($server->server_type ? $this->escape($server->server_type) : '—').' | '
                .($server->hostname ? '`'.$this->escape($server->hostname).'`' : '—').' | '
                .($server->ip_address ? $this->escape($server->ip_address) : '—').' | '
                .($server->port ?: '—').' | '
                .($server->location ? $this->escape($server->location) : '—').' |';
        }

        return $lines;
    }

    private function buildProcesses(System $system): string
    {
        return $this->wrapDocument($system, SystemDocumentTypes::PROCESSES, $this->buildProcessesBody($system));
    }

    /** @return list<string> */
    private function buildProcessesBody(System $system): array
    {
        if ($system->bpmns->isEmpty()) {
            return ['_No BPMN or sequence diagrams linked to this system._'];
        }

        $lines = [
            '| Diagram | Type | Created |',
            '| --- | --- | --- |',
        ];

        foreach ($system->bpmns as $bpmn) {
            $type = $bpmn->isSequence() ? 'Sequence' : 'BPMN';
            $lines[] = '| '.$this->escape($bpmn->name).' | '.$type.' | '
                .$bpmn->created_at->format('Y-m-d').' |';
        }

        return $lines;
    }

    private function buildDataSchemas(System $system): string
    {
        return $this->wrapDocument($system, SystemDocumentTypes::DATA_SCHEMAS, $this->buildDataSchemasBody($system));
    }

    /** @return list<string> */
    private function buildDataSchemasBody(System $system): array
    {
        if ($system->platformSchemas->isEmpty()) {
            return ['_No platform data schemas registered for this system._'];
        }

        $lines = [];

        foreach ($system->platformSchemas as $schema) {
            $lines[] = '### '.$this->escape($schema->name);
            $lines[] = '';
            $lines[] = '- **Layer:** `'.$this->escape($schema->data_layer).'`';
            $lines[] = '- **Source Type:** '.($schema->source_type ? $this->escape($schema->source_type) : '—');
            $lines[] = '- **Version:** '.($schema->version ? '`'.$this->escape($schema->version).'`' : '—');

            if ($schema->description) {
                $lines[] = '- **Description:** '.$this->escape($schema->description);
            }

            if ($schema->fields->isNotEmpty()) {
                $lines[] = '';
                $lines[] = '| Field | Type | Nullable |';
                $lines[] = '| --- | --- | --- |';

                foreach ($schema->fields as $field) {
                    $fieldName = $field->native_name ?: $field->native_path ?: 'Field #'.$field->id;
                    $lines[] = '| '.$this->escape($fieldName).' | '
                        .($field->data_type ? '`'.$this->escape($field->data_type).'`' : '—').' | '
                        .($field->nullable ? 'Yes' : 'No').' |';
                }
            }

            $lines[] = '';
        }

        return $lines;
    }

    /**
     * @param  list<string>  $body
     */
    private function wrapDocument(System $system, string $type, array $body): string
    {
        $lines = [
            '# '.$this->escape($system->name).' — '.SystemDocumentTypes::label($type),
            '',
            '> Auto-generated by OpenITS on '.now()->format('Y-m-d H:i').' UTC',
            '',
        ];

        return implode("\n", array_merge($lines, $body));
    }

    private function escape(?string $value): string
    {
        if ($value === null || $value === '') {
            return '';
        }

        return str_replace(['|', "\n", "\r"], ['\\|', ' ', ' '], $value);
    }
}
